# augmentation set = TAU_0
python train_sed.py --conf_file ./confs/default_1.yaml # invariance layer = 1, seed = 42 
python train_sed.py --conf_file ./confs/default_2.yaml # invariance layer = 1, seed = 564537
python train_sed.py --conf_file ./confs/default_3.yaml # invariance layer = 1, seed = 54316782

# augmentation set = TAU_1
python irct_train_sed.py --conf_file ./confs/irct_t1_l1_1.yaml # invariance layer = 1, seed = 42 
python irct_train_sed.py --conf_file ./confs/irct_t1_l1_2.yaml # invariance layer = 1, seed = 564537
python irct_train_sed.py --conf_file ./confs/irct_t1_l1_3.yaml # invariance layer = 1, seed = 54316782
python irct_train_sed.py --conf_file ./confs/irct_t1_l2_1.yaml # invariance layer = 2, seed = 42 
python irct_train_sed.py --conf_file ./confs/irct_t1_l2_2.yaml # invariance layer = 2, seed = 564537
python irct_train_sed.py --conf_file ./confs/irct_t1_l2_3.yaml # invariance layer = 2, seed = 54316782
python irct_train_sed.py --conf_file ./confs/irct_t1_l3_1.yaml # invariance layer = 3, seed = 42 
python irct_train_sed.py --conf_file ./confs/irct_t1_l3_2.yaml # invariance layer = 3, seed = 564537
python irct_train_sed.py --conf_file ./confs/irct_t1_l3_3.yaml # invariance layer = 3, seed = 54316782
python irct_train_sed.py --conf_file ./confs/irct_t1_l4_1.yaml # invariance layer = 4, seed = 42 
python irct_train_sed.py --conf_file ./confs/irct_t1_l4_2.yaml # invariance layer = 4, seed = 564537
python irct_train_sed.py --conf_file ./confs/irct_t1_l4_3.yaml # invariance layer = 4, seed = 54316782
python irct_train_sed.py --conf_file ./confs/irct_t1_l5_1.yaml # invariance layer = 5, seed = 42 
python irct_train_sed.py --conf_file ./confs/irct_t1_l5_2.yaml # invariance layer = 5, seed = 564537
python irct_train_sed.py --conf_file ./confs/irct_t1_l5_3.yaml # invariance layer = 5, seed = 54316782
python irct_train_sed.py --conf_file ./confs/irct_t1_l6_1.yaml # invariance layer = 6, seed = 42 
python irct_train_sed.py --conf_file ./confs/irct_t1_l6_2.yaml # invariance layer = 6, seed = 564537
python irct_train_sed.py --conf_file ./confs/irct_t1_l6_3.yaml # invariance layer = 6, seed = 54316782
python irct_train_sed.py --conf_file ./confs/irct_t1_l7_1.yaml # invariance layer = 7, seed = 42 
python irct_train_sed.py --conf_file ./confs/irct_t1_l7_2.yaml # invariance layer = 7, seed = 564537
python irct_train_sed.py --conf_file ./confs/irct_t1_l7_3.yaml # invariance layer = 7, seed = 54316782
python irct_train_sed.py --conf_file ./confs/irct_t1_l8_1.yaml # invariance layer = 8, seed = 42 
python irct_train_sed.py --conf_file ./confs/irct_t1_l8_2.yaml # invariance layer = 8, seed = 564537
python irct_train_sed.py --conf_file ./confs/irct_t1_l8_3.yaml # invariance layer = 8, seed = 54316782
python irct_train_sed.py --conf_file ./confs/irct_t1_l9_1.yaml # invariance layer = 9, seed = 42 
python irct_train_sed.py --conf_file ./confs/irct_t1_l9_2.yaml # invariance layer = 9, seed = 564537
python irct_train_sed.py --conf_file ./confs/irct_t1_l9_3.yaml # invariance layer = 9, seed = 54316782

# augmentation set = TAU_2
python irct_train_sed.py --conf_file ./confs/irct_t2_l1_1.yaml # invariance layer = 1, seed = 42 
python irct_train_sed.py --conf_file ./confs/irct_t2_l1_2.yaml # invariance layer = 1, seed = 564537
python irct_train_sed.py --conf_file ./confs/irct_t2_l1_3.yaml # invariance layer = 1, seed = 54316782
python irct_train_sed.py --conf_file ./confs/irct_t2_l2_1.yaml # invariance layer = 2, seed = 42 
python irct_train_sed.py --conf_file ./confs/irct_t2_l2_2.yaml # invariance layer = 2, seed = 564537
python irct_train_sed.py --conf_file ./confs/irct_t2_l2_3.yaml # invariance layer = 2, seed = 54316782
python irct_train_sed.py --conf_file ./confs/irct_t2_l3_1.yaml # invariance layer = 3, seed = 42 
python irct_train_sed.py --conf_file ./confs/irct_t2_l3_2.yaml # invariance layer = 3, seed = 564537
python irct_train_sed.py --conf_file ./confs/irct_t2_l3_3.yaml # invariance layer = 3, seed = 54316782
python irct_train_sed.py --conf_file ./confs/irct_t2_l4_1.yaml # invariance layer = 4, seed = 42 
python irct_train_sed.py --conf_file ./confs/irct_t2_l4_2.yaml # invariance layer = 4, seed = 564537
python irct_train_sed.py --conf_file ./confs/irct_t2_l4_3.yaml # invariance layer = 4, seed = 54316782
python irct_train_sed.py --conf_file ./confs/irct_t2_l5_1.yaml # invariance layer = 5, seed = 42 
python irct_train_sed.py --conf_file ./confs/irct_t2_l5_2.yaml # invariance layer = 5, seed = 564537
python irct_train_sed.py --conf_file ./confs/irct_t2_l5_3.yaml # invariance layer = 5, seed = 54316782
python irct_train_sed.py --conf_file ./confs/irct_t2_l6_1.yaml # invariance layer = 6, seed = 42 
python irct_train_sed.py --conf_file ./confs/irct_t2_l6_2.yaml # invariance layer = 6, seed = 564537
python irct_train_sed.py --conf_file ./confs/irct_t2_l6_3.yaml # invariance layer = 6, seed = 54316782
python irct_train_sed.py --conf_file ./confs/irct_t2_l7_1.yaml # invariance layer = 7, seed = 42 
python irct_train_sed.py --conf_file ./confs/irct_t2_l7_2.yaml # invariance layer = 7, seed = 564537
python irct_train_sed.py --conf_file ./confs/irct_t2_l7_3.yaml # invariance layer = 7, seed = 54316782
python irct_train_sed.py --conf_file ./confs/irct_t2_l8_1.yaml # invariance layer = 8, seed = 42 
python irct_train_sed.py --conf_file ./confs/irct_t2_l8_2.yaml # invariance layer = 8, seed = 564537
python irct_train_sed.py --conf_file ./confs/irct_t2_l8_3.yaml # invariance layer = 8, seed = 54316782
python irct_train_sed.py --conf_file ./confs/irct_t2_l9_1.yaml # invariance layer = 9, seed = 42 
python irct_train_sed.py --conf_file ./confs/irct_t2_l9_2.yaml # invariance layer = 9, seed = 564537
python irct_train_sed.py --conf_file ./confs/irct_t2_l9_3.yaml # invariance layer = 9, seed = 54316782

# probe complexity = 8
python probe_train_sed.py --conf_file ./confs/probe_h8_l1_1.yaml # extraction layer = 1, seed = 42 
python probe_train_sed.py --conf_file ./confs/probe_h8_l1_2.yaml # extraction layer = 1, seed = 564537
python probe_train_sed.py --conf_file ./confs/probe_h8_l1_3.yaml # extraction layer = 1, seed = 54316782
python probe_train_sed.py --conf_file ./confs/probe_h8_l2_1.yaml # extraction layer = 2, seed = 42 
python probe_train_sed.py --conf_file ./confs/probe_h8_l2_2.yaml # extraction layer = 2, seed = 564537
python probe_train_sed.py --conf_file ./confs/probe_h8_l2_3.yaml # extraction layer = 2, seed = 54316782
python probe_train_sed.py --conf_file ./confs/probe_h8_l3_1.yaml # extraction layer = 3, seed = 42 
python probe_train_sed.py --conf_file ./confs/probe_h8_l3_2.yaml # extraction layer = 3, seed = 564537
python probe_train_sed.py --conf_file ./confs/probe_h8_l3_3.yaml # extraction layer = 3, seed = 54316782
python probe_train_sed.py --conf_file ./confs/probe_h8_l4_1.yaml # extraction layer = 4, seed = 42 
python probe_train_sed.py --conf_file ./confs/probe_h8_l4_2.yaml # extraction layer = 4, seed = 564537
python probe_train_sed.py --conf_file ./confs/probe_h8_l4_3.yaml # extraction layer = 4, seed = 54316782
python probe_train_sed.py --conf_file ./confs/probe_h8_l5_1.yaml # extraction layer = 5, seed = 42 
python probe_train_sed.py --conf_file ./confs/probe_h8_l5_2.yaml # extraction layer = 5, seed = 564537
python probe_train_sed.py --conf_file ./confs/probe_h8_l5_3.yaml # extraction layer = 5, seed = 54316782
python probe_train_sed.py --conf_file ./confs/probe_h8_l6_1.yaml # extraction layer = 6, seed = 42 
python probe_train_sed.py --conf_file ./confs/probe_h8_l6_2.yaml # extraction layer = 6, seed = 564537
python probe_train_sed.py --conf_file ./confs/probe_h8_l6_3.yaml # extraction layer = 6, seed = 54316782
python probe_train_sed.py --conf_file ./confs/probe_h8_l7_1.yaml # extraction layer = 7, seed = 42 
python probe_train_sed.py --conf_file ./confs/probe_h8_l7_2.yaml # extraction layer = 7, seed = 564537
python probe_train_sed.py --conf_file ./confs/probe_h8_l7_3.yaml # extraction layer = 7, seed = 54316782
python probe_train_sed.py --conf_file ./confs/probe_h8_l8_1.yaml # extraction layer = 8, seed = 42 
python probe_train_sed.py --conf_file ./confs/probe_h8_l8_2.yaml # extraction layer = 8, seed = 564537
python probe_train_sed.py --conf_file ./confs/probe_h8_l8_3.yaml # extraction layer = 8, seed = 54316782

# probe complexity = 16
python probe_train_sed.py --conf_file ./confs/probe_h16_l1_1.yaml # extraction layer = 1, seed = 42 
python probe_train_sed.py --conf_file ./confs/probe_h16_l1_2.yaml # extraction layer = 1, seed = 564537
python probe_train_sed.py --conf_file ./confs/probe_h16_l1_3.yaml # extraction layer = 1, seed = 54316782
python probe_train_sed.py --conf_file ./confs/probe_h16_l2_1.yaml # extraction layer = 2, seed = 42 
python probe_train_sed.py --conf_file ./confs/probe_h16_l2_2.yaml # extraction layer = 2, seed = 564537
python probe_train_sed.py --conf_file ./confs/probe_h16_l2_3.yaml # extraction layer = 2, seed = 54316782
python probe_train_sed.py --conf_file ./confs/probe_h16_l3_1.yaml # extraction layer = 3, seed = 42 
python probe_train_sed.py --conf_file ./confs/probe_h16_l3_2.yaml # extraction layer = 3, seed = 564537
python probe_train_sed.py --conf_file ./confs/probe_h16_l3_3.yaml # extraction layer = 3, seed = 54316782
python probe_train_sed.py --conf_file ./confs/probe_h16_l4_1.yaml # extraction layer = 4, seed = 42 
python probe_train_sed.py --conf_file ./confs/probe_h16_l4_2.yaml # extraction layer = 4, seed = 564537
python probe_train_sed.py --conf_file ./confs/probe_h16_l4_3.yaml # extraction layer = 4, seed = 54316782
python probe_train_sed.py --conf_file ./confs/probe_h16_l5_1.yaml # extraction layer = 5, seed = 42 
python probe_train_sed.py --conf_file ./confs/probe_h16_l5_2.yaml # extraction layer = 5, seed = 564537
python probe_train_sed.py --conf_file ./confs/probe_h16_l5_3.yaml # extraction layer = 5, seed = 54316782
python probe_train_sed.py --conf_file ./confs/probe_h16_l6_1.yaml # extraction layer = 6, seed = 42 
python probe_train_sed.py --conf_file ./confs/probe_h16_l6_2.yaml # extraction layer = 6, seed = 564537
python probe_train_sed.py --conf_file ./confs/probe_h16_l6_3.yaml # extraction layer = 6, seed = 54316782
python probe_train_sed.py --conf_file ./confs/probe_h16_l7_1.yaml # extraction layer = 7, seed = 42 
python probe_train_sed.py --conf_file ./confs/probe_h16_l7_2.yaml # extraction layer = 7, seed = 564537
python probe_train_sed.py --conf_file ./confs/probe_h16_l7_3.yaml # extraction layer = 7, seed = 54316782
python probe_train_sed.py --conf_file ./confs/probe_h16_l8_1.yaml # extraction layer = 8, seed = 42 
python probe_train_sed.py --conf_file ./confs/probe_h16_l8_2.yaml # extraction layer = 8, seed = 564537
python probe_train_sed.py --conf_file ./confs/probe_h16_l8_3.yaml # extraction layer = 8, seed = 54316782

# probe complexity = 32
python probe_train_sed.py --conf_file ./confs/probe_h32_l1_1.yaml # extraction layer = 1, seed = 42 
python probe_train_sed.py --conf_file ./confs/probe_h32_l1_2.yaml # extraction layer = 1, seed = 564537
python probe_train_sed.py --conf_file ./confs/probe_h32_l1_3.yaml # extraction layer = 1, seed = 54316782
python probe_train_sed.py --conf_file ./confs/probe_h32_l2_1.yaml # extraction layer = 2, seed = 42 
python probe_train_sed.py --conf_file ./confs/probe_h32_l2_2.yaml # extraction layer = 2, seed = 564537
python probe_train_sed.py --conf_file ./confs/probe_h32_l2_3.yaml # extraction layer = 2, seed = 54316782
python probe_train_sed.py --conf_file ./confs/probe_h32_l3_1.yaml # extraction layer = 3, seed = 42 
python probe_train_sed.py --conf_file ./confs/probe_h32_l3_2.yaml # extraction layer = 3, seed = 564537
python probe_train_sed.py --conf_file ./confs/probe_h32_l3_3.yaml # extraction layer = 3, seed = 54316782
python probe_train_sed.py --conf_file ./confs/probe_h32_l4_1.yaml # extraction layer = 4, seed = 42 
python probe_train_sed.py --conf_file ./confs/probe_h32_l4_2.yaml # extraction layer = 4, seed = 564537
python probe_train_sed.py --conf_file ./confs/probe_h32_l4_3.yaml # extraction layer = 4, seed = 54316782
python probe_train_sed.py --conf_file ./confs/probe_h32_l5_1.yaml # extraction layer = 5, seed = 42 
python probe_train_sed.py --conf_file ./confs/probe_h32_l5_2.yaml # extraction layer = 5, seed = 564537
python probe_train_sed.py --conf_file ./confs/probe_h32_l5_3.yaml # extraction layer = 5, seed = 54316782
python probe_train_sed.py --conf_file ./confs/probe_h32_l6_1.yaml # extraction layer = 6, seed = 42 
python probe_train_sed.py --conf_file ./confs/probe_h32_l6_2.yaml # extraction layer = 6, seed = 564537
python probe_train_sed.py --conf_file ./confs/probe_h32_l6_3.yaml # extraction layer = 6, seed = 54316782
python probe_train_sed.py --conf_file ./confs/probe_h32_l7_1.yaml # extraction layer = 7, seed = 42 
python probe_train_sed.py --conf_file ./confs/probe_h32_l7_2.yaml # extraction layer = 7, seed = 564537
python probe_train_sed.py --conf_file ./confs/probe_h32_l7_3.yaml # extraction layer = 7, seed = 54316782
python probe_train_sed.py --conf_file ./confs/probe_h32_l8_1.yaml # extraction layer = 8, seed = 42 
python probe_train_sed.py --conf_file ./confs/probe_h32_l8_2.yaml # extraction layer = 8, seed = 564537
python probe_train_sed.py --conf_file ./confs/probe_h32_l8_3.yaml # extraction layer = 8, seed = 54316782
